name: 'Setup EDAMAME Posture'
description: 'Download and start EDAMAME Posture'
inputs:
  edamame_user:
    description: 'EDAMAME Posture User'
    required: false
  edamame_domain:
    description: 'EDAMAME Posture Domain'
    required: false
  edamame_pin:
    description: 'EDAMAME Posture PIN'
    required: false
  edamame_id:
    description: 'EDAMAME identifier suffix'
    required: false
  auto_remediate:
    description: 'Automatically remediate posture issues'
    required: false
    default: 'false'
  skip_remediations:
    description: 'Remediations to skip (comma separated)'
    required: false
  network_scan:
    description: 'Scan network for critical devices'
    required: false
    default: 'false'

runs:
  using: 'composite'

  steps:

    - name: Dependencies
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          choco install wget
        fi
      shell: bash

    - name: Download EDAMAME Posture binary
      run: |
        # Position the binary in the home folder of the runner
        cd ..
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          wget https://edamame-posture.s3.eu-west-1.amazonaws.com/dev/linux/0.3.84/edamame_posture
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          wget https://edamame-posture.s3.eu-west-1.amazonaws.com/dev/macos/0.3.84/edamame_posture
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          wget https://edamame-posture.s3.eu-west-1.amazonaws.com/dev/windows/0.3.84/edamame_posture.exe
        else
          echo "Unsupported OS: $RUNNER_OS"
          exit 1
        fi
        chmod u+x edamame_posture*
      shell: bash

    - name: Show initial posture
      run: |
        cd ..
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          # No sudo on Windows
          ./edamame_posture.exe score
        else
          sudo ./edamame_posture score
        fi
      shell: bash

    - name: Auto remediate posture issues if requested
      run: |
        cd ..
        if [[ "${{ inputs.auto_remediate }}" == "true" ]]; then
          if [[ "${{ inputs.skip_remediations }}" == "" ]]; then
            echo "No remediations to skip"
            if [[ "$RUNNER_OS" == "Windows" ]]; then
              # No sudo on Windows
              ./edamame_posture.exe remediate
            else
              sudo ./edamame_posture remediate
            fi
          else 
            echo "Skipping remediations: ${{ inputs.skip_remediations }}"
            if [[ "$RUNNER_OS" == "Windows" ]]; then
              # No sudo on Windows
              ./edamame_posture.exe remediate "${{ inputs.skip_remediations }}"
            else
              sudo ./edamame_posture remediate "${{ inputs.skip_remediations }}"
            fi
          fi
        fi
      shell: bash
      
    - name: Start EDAMAME Posture process and wait for connection if all arguments are provided, skip otherwise
      run: |
        cd ..
        # Check if all arguments are provided
        if [[ -n "${{ inputs.edamame_user }}" && -n "${{ inputs.edamame_domain }}" && -n "${{ inputs.edamame_pin }}" && -n "${{ inputs.edamame_id }}" ]]; then
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            # No sudo on Windows
            ./edamame_posture.exe start "${{ inputs.edamame_user }}" "${{ inputs.edamame_domain }}" "${{ inputs.edamame_pin }}" "${{ inputs.edamame_id }}" "${{ inputs.network_scan }}"
            ./edamame_posture.exe wait-for-connection
          else
            sudo ./edamame_posture start "${{ inputs.edamame_user }}" "${{ inputs.edamame_domain }}" "${{ inputs.edamame_pin }}" "${{ inputs.edamame_id }}" "${{ inputs.network_scan }}"
            sudo ./edamame_posture wait-for-connection
          fi
        else
          # Check if only a partial set of mandatory arguments is provided
          if [[ -n "${{ inputs.edamame_user }}${{ inputs.edamame_domain }}${{ inputs.edamame_pin }}${{ inputs.edamame_id }}" ]]; then
            echo "Please provide all required arguments: edamame_user, edamame_domain, edamame_pin, edamame_id"
          exit 1
          fi
        fi
      shell: bash


