name: Test

on:
  workflow_dispatch:

jobs:
  test-edamame-posture:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Run the EDAMAME Posture setup action
      - name: Run EDAMAME Posture Setup Action
        uses: ./ # Use the local action definition (action.yaml)
        with:
          edamame_user: ${{ vars.EDAMAME_POSTURE_USER }}
          edamame_domain: ${{ vars.EDAMAME_POSTURE_DOMAIN }}
          edamame_pin: ${{ secrets.EDAMAME_POSTURE_PIN }}
          edamame_id: ${{ github.run_id }}
          checkout: true

      # Add a verification step to ensure the action completed successfully
      - name: Verify Action Execution
        run: |
          echo "EDAMAME Posture Setup completed successfully"
