name: Test

on:
  schedule:
    # Run daily at 01:00 UTC
    - cron: '0 1 * * *'
  workflow_dispatch:
  push:
    branches:
      - 'dev'
      - 'main'
      
# Auto cancel previous runs if they were not completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-edamame-posture:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90

    steps:
      # We don't use the EDAMAME Posture Action here, because we want to fully test the action.yml file
      - name: Checkout
        uses: actions/checkout@v4

      # Test start
      - name: Test start
        id: test-start
        uses: ./ # Use the local action definition (action.yaml)
        with:
          edamame_user: ${{ vars.EDAMAME_POSTURE_USER }}
          edamame_domain: ${{ vars.EDAMAME_POSTURE_DOMAIN }}
          edamame_pin: ${{ secrets.EDAMAME_POSTURE_PIN }}
          edamame_id: ${{ github.run_id }}
          # Don't checkout the repo, we already did that in the previous step
          checkout: false
          report_email: dev@edamame.tech
          # Set to true to test the whitelist creation
          network_scan: true
        continue-on-error: true
        
      # Test check-policy (local)
      - name: Test check-policy (local)
        id: test-check-policy-local
        uses: ./
        with:
          edamame_minimum_score: 1.0
          edamame_mandatory_threats: "encrypted disk disabled"
          edamame_mandatory_prefixes: ""
        continue-on-error: true
        
      # Test check-policy-for-domain
      - name: Test check-policy-for-domain
        id: test-check-policy-for-domain
        uses: ./
        with:
          edamame_domain: ${{ vars.EDAMAME_POSTURE_DOMAIN }}
          edamame_policy: "Github"
        continue-on-error: true

      # Test check-policy (local) with error
      - name: Test check-policy (local) with error
        id: test-check-policy-local-error
        uses: ./
        with:
          edamame_minimum_score: 5.0
          edamame_mandatory_threats: "no EPP"
          edamame_mandatory_prefixes: ""
        continue-on-error: true
      
      # Test check-policy-for-domain with error
      - name: Test check-policy-for-domain with error
        id: test-check-policy-for-domain-error
        uses: ./
        with:
          edamame_domain: ${{ vars.EDAMAME_POSTURE_DOMAIN }}
          edamame_policy: "Invalid policy"
        continue-on-error: true

      # Test dump sessions
      - name: Test dump sessions
        id: test-dump-sessions
        uses: ./
        with:
          dump_sessions_log: true
          exit_on_whitelist_exceptions: false
        continue-on-error: true

      # Test create custom whitelists on macOS and Linux
      - name: Test create custom whitelists on macOS and Linux
        id: test-create-custom-whitelist
        if: runner.os == 'macos' || runner.os == 'linux'
        uses: ./
        with:
          create_custom_whitelists: true
          custom_whitelists_path: custom_whitelists.json
        continue-on-error: true
        
      # Test set custom whitelist
      - name: Test set custom whitelist
        id: test-set-custom-whitelist
        if: (runner.os == 'macos' || runner.os == 'linux') && steps.test-create-custom-whitelist.outcome == 'success'
        uses: ./
        with:
          set_custom_whitelists: true
          custom_whitelists_path: custom_whitelists.json
        continue-on-error: true

      - name: Test stop
        id: test-stop
        uses: ./
        with:
          stop: true
        continue-on-error: true
        
      # Test disconnected mode
      - name: Test disconnected mode
        id: test-disconnected-mode
        uses: ./
        with:
          disconnected_mode: true
          network_scan: true
          whitelist: github
          edamame_minimum_score: 1.0
          edamame_mandatory_threats: "encrypted disk disabled"
        continue-on-error: true

      # Test get sessions with disconnected mode
      - name: Test sessions with disconnected mode
        id: test-sessions-disconnected
        if: steps.test-disconnected-mode.outcome == 'success'
        uses: ./
        with:
          exit_on_whitelist_exceptions: false
          dump_sessions_log: true
        continue-on-error: true
        
      - name: Slack alerts
        if: |
          steps.test-start.outcome != 'success' || 
          steps.test-check-policy-local.outcome != 'success' || 
          steps.test-check-policy-for-domain.outcome != 'success' || 
          steps.test-check-policy-local-error.outcome == 'success' || 
          steps.test-check-policy-for-domain-error.outcome == 'success' || 
          steps.test-dump-sessions.outcome != 'success' || 
          (runner.os != 'Windows' && steps.test-create-custom-whitelist.outcome != 'success') || 
          (runner.os != 'Windows' && steps.test-set-custom-whitelist.outcome != 'success') ||
          steps.test-stop.outcome != 'success' ||
          steps.test-disconnected-mode.outcome != 'success' ||
          steps.test-sessions-disconnected.outcome != 'success'
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072J0U9TH7'
          slack-message: |
            *Test Results for ${{ github.repository }} (${{ runner.os }})*:
            - Start: ${{ steps.test-start.outcome == 'success' && '✅ Success' || '❌ Failed' }}
            - Check Policy (Local): ${{ steps.test-check-policy-local.outcome == 'success' && '✅ Success' || '❌ Failed' }}
            - Check Policy (Domain): ${{ steps.test-check-policy-for-domain.outcome == 'success' && '✅ Success' || '❌ Failed' }}
            - Check Policy Error Test: ${{ steps.test-check-policy-local-error.outcome != 'success' && '✅ Success' || '❌ Failed' }}
            - Check Domain Policy Error Test: ${{ steps.test-check-policy-for-domain-error.outcome != 'success' && '✅ Success' || '❌ Failed' }}
            - Dump Sessions: ${{ steps.test-dump-sessions.outcome == 'success' && '✅ Success' || '❌ Failed' }}
            - Create Custom Whitelist: ${{ (runner.os == 'Windows' || steps.test-create-custom-whitelist.outcome == 'success') && '✅ Success' || '❌ Failed' }}
            - Set Custom Whitelist: ${{ (runner.os == 'Windows' || steps.test-set-custom-whitelist.outcome == 'success') && '✅ Success' || '❌ Failed' }}
            - Disconnected Mode: ${{ steps.test-disconnected-mode.outcome == 'success' && '✅ Success' || '❌ Failed' }}
            - Sessions Disconnected: ${{ steps.test-sessions-disconnected.outcome == 'success' && '✅ Success' || '❌ Failed' }}
            Branch: ${{ github.ref }}
            More details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Fail job if tests failed
        if: |
          steps.test-start.outcome != 'success' || 
          steps.test-check-policy-local.outcome != 'success' || 
          steps.test-check-policy-for-domain.outcome != 'success' || 
          steps.test-check-policy-local-error.outcome == 'success' || 
          steps.test-check-policy-for-domain-error.outcome == 'success' || 
          steps.test-dump-sessions.outcome != 'success' || 
          (runner.os != 'Windows' && steps.test-create-custom-whitelist.outcome != 'success') || 
          (runner.os != 'Windows' && steps.test-set-custom-whitelist.outcome != 'success') ||
          steps.test-disconnected-mode.outcome != 'success' ||
          steps.test-sessions-disconnected.outcome != 'success'
        run: |
          echo "Forcing job to fail because tests did not succeed."
          exit 1